name: googlesigninfirebase
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0

  # Google Sign-In and Firebase Authentication dependencies
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1

  # Google Icon
  font_awesome_flutter: ^10.8.0

  #State Management
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
